### ISSUE TITLE
Quickstart new cluster/vpc -> curl: (6) Could not resolve host: rancher.aws.private

### ISSUE THREAD

**Issue by jforge** [aws-quickstart/quickstart-eks-rancher#26]
Naive approach: Following the recommended https://aws-quickstart.github.io/quickstart-eks-rancher/ with a new Cluster and new VPC deploys the Cloudformation stack successfully, but testing in the bastion host (named "EKSBastion" in the EC2 instances) fails.

The guide expects this call to succeed, but 
```
curl -k https://rancher.aws.private
curl: (6) Could not resolve host: rancher.aws.private
```

What do I miss to solve that issue?

**Comment by davmayd** [comment]
The SSM document was failing to deploy due to IAM restrictions, the issue is now resolved.

**Comment by jforge** [comment]
I've just repeated the setup and still get the message above (region: eu-central-1).
I see no errors in the cfn stacks, no IAM restrictions (admin), the SSM document is available without noticeable problems.

What should I explicitly look for in order to find the root cause, so that II can resolve that hostname?

**Comment by davmayd** [comment]
I'm attempting to replicate the issue in eu-central-1. In the meantime, can you open Systems Manager > Automation and see if there are any errors in the automation document execution?

**Comment by jforge** [comment]
Thanks for this and the key information. There is an issue in the Automation document execution:

Executed automation: EKS-with-Rancher-EKSStack-...-RancherStack-...-RancherInstallerSetup-...

I see 8 stepss, 4 are pending, 3 success, first in error state:

```
... | 1 | CreateStack | aws:createStack | Failed | Tue, 17 Aug 2021 14:35:50 GMT | Tue, 17 Aug 2021 14:35:54 GMT
... | 2 | CFNSignalEnd | aws:branch | Success | Tue, 17 Aug 2021 14:35:54 GMT | Tue, 17 Aug 2021 14:35:54 GMT
... | 3 | signalsuccess | aws:executeAwsApi | Success | Tue, 17 Aug 2021 14:35:54 GMT | Tue, 17 Aug 2021 14:35:55 GMT
... | 4 | deleteStack | aws:deleteStack | Success | Tue, 17 Aug 2021 14:35:55 GMT | Tue, 17 Aug 2021 14:35:58 GMT
... | - | getInstanceId | aws:executeAwsApi | Pending | - | -
... | - | DownloadAndRunRancherInstallScript | aws:runCommand | Pending | - | -
... | - | sleepend | aws:sleep | Pending | - | -
... | - | signalfailure | aws:executeAwsApi | Pending | - | -
```

aws:createStack failed with the message:

> Automation Step Execution fails when it is creating a CloudFormation stack. Get Exception from CreateStack API of cloudformation Service. Exception Message from CreateStack API: [Template error: unresolved condition dependency UsingDefaultBucket in Fn::If (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: 2a59ea25-f957-4e1c-9bb4-855a69447a50; Proxy: null)]. Please refer to Automation Service Troubleshooting Guide for more diagnosis details.

Action: aws:createStack
Start time: Tue, 17 Aug 2021 14:35:50 GMT
End time: Tue, 17 Aug 2021 14:35:54 GMT
onFailure: step:CFNSignalEnd


In the source stacks I see e.g.:
```
Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']
```
or
```
!If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
```

The troubleshooting guide didn't help me so far, so what is the issue? Existence of this bucket in the correct region?

I know the quickstart form does not have input validation (e.g. for the cluster name) and throws errors afterwards,
but I really don't see other errors, especially not in the event of the several (nested) cfn stacks.
